export const dictionary = {
    id: {
    subtitle: "Sistem Buku Tamu & Reservasi Digital",
    tabNew: "Daftar",
    tabOld: "Login",
    labelNik: "NIK",
    placeholderNik: "Masukkan NIK Anda",
    labelWa: "No. WhatsApp",
    placeholderWa: "contoh : 6281222081400",
    btnCheck: "Cek Data Profil",
    btnChecking: "Memverifikasi...",
    labelNama: "Nama Lengkap",
    placeholderNama: "Masukkan nama lengkap",
    labelInstansi: "Instansi / Sekolah",
    placeholderInstansi: "Asal instansi",
    labelEmail: "Email",
    labelKeperluan: "Keperluan",
    placeholderKeperluan: "Koordinasi Projek / Rapat Dinas",
    labelMenemui: "Ingin Menemui Siapa",
    placeholderMenemui: "Nama Guru / Staff",
    labelTtd: "Tanda Tangan Digital",
    btnClearTtd: "Bersihkan Ulang Tanda Tangan",
    btnSubmit: "Dapatkan QR Code",
    btnSubmitting: "Sedang Memproses...",
    ticketSuccess: "Tiket Kunjungan Berhasil!",
    ticketDesc: "Tunjukkan QR Code ini kepada petugas gerbang/resepsionis.",
    btnGallery: "Simpan ke Galeri",
    btnDashboard: "➡️ Selanjutnya ke Dashboard",
    peringatan: "Mohon isi NIK dan Nomor WhatsApp Anda Terlebih Dahulu!",
    registerT: "Jika anda baru pertama kali memakai SowanQR, diharapkan untuk daftar terlebih dahulu",
    loginT: "Silakan verifikasi data Anda untuk langsung masuk ke Dashboard",
    dataF: "Data tidak ditemukan. Silakan mendaftar sebagai Tamu Baru.",
    handC: "Mohon isi tanda tangan terlebih dahulu!",
    errorA : "Terjadi kesalahan sistem",
    errorR: "Gagal memproses pendaftaran"
  },
  en: {
    subtitle: "Digital Visitor Book & Reservation System",
    tabNew: "Register",
    tabOld: "Login",
    labelNik: "National ID Number (NIK)",
    placeholderNik: "Enter your NIK number",
    labelWa: "WhatsApp Number",
    placeholderWa: "example : 6281222081400",
    btnCheck: "Verify Profile",
    btnChecking: "Verifying...",
    labelNama: "Full Name",
    placeholderNama: "Enter your full name",
    labelInstansi: "Institution / School",
    placeholderInstansi: "Origin institution",
    labelEmail: "Email Address",
    labelKeperluan: "Purpose of Visit",
    placeholderKeperluan: "Project Coordination / Meeting",
    labelMenemui: "Person to Meet",
    placeholderMenemui: "Teacher / Staff Name",
    labelTtd: "Digital Signature",
    btnClearTtd: "Clear Signature Canvas",
    btnSubmit: "Get QR Code",
    btnSubmitting: "Processing...",
    ticketSuccess: "Visitor Ticket Created Successfully!",
    ticketDesc: "Show this QR Code to the gate officer or receptionist.",
    btnGallery: "Save to Gallery",
    btnDashboard: "➡️ Proceed to Dashboard",
    peringatan: "Please fill in your NIK and WhatsApp number first",
    night: "Night Mode",
    noon: "Day Mode",
    registerT: "If this is your first time using SowanQR, please register first.",
    loginT: "Please verify your data to directly enter the Web",
    dataF: "Data not found. Please register as a New Guest.",
    handC: "Please fill in your signature first!",
    errorA: "A system error occurred",
    errorR: "Failed to process registration"
  }
};
