export const dictionary = {
    id: {
    subtitle: "Sistem Buku Tamu & Reservasi Digital",
    tabNew: "Daftar",
    tabOld: "Login",
    labelNik: "NIK",
    placeholderNik: "Masukkan 16 digit NIK Anda",
    labelWa: "No. WhatsApp",
    placeholderWa: "contoh : 081222081400",
    btnCheck: "Cek Data Profil",
    btnChecking: "Memverifikasi...",
    labelNama: "Nama Lengkap",
    placeholderNama: "Masukkan nama lengkap",
    labelInstansi: "Instansi / Sekolah",
    placeholderInstansi: "Asal instansi",
    labelEmail: "Email",
    labelKeperluan: "Keperluan",
    placeholderKeperluan: "Koordinasi Projek / Rapat Dinas",
    labelMenemui: "Ingin Menemui Siapa",
    placeholderMenemui: "Nama Guru / Staff",
    labelTtd: "Tanda Tangan Digital",
    btnClearTtd: "Bersihkan Ulang Tanda Tangan",
    btnSubmit: "Dapatkan QR Code",
    btnSubmitting: "Sedang Memproses...",
    ticketSuccess: "Tiket Kunjungan Berhasil!",
    ticketDesc: "Tunjukkan QR Code ini kepada petugas gerbang/resepsionis.",
    btnGallery: "Simpan ke Galeri",
    btnDashboard: "Selanjutnya ke Dashboard",
    peringatan: "Mohon isi NIK dan Nomor WhatsApp Anda Terlebih Dahulu!",
    registerT: "Jika anda baru pertama kali memakai SowanQR, diharapkan untuk daftar terlebih dahulu",
    loginT: "Silakan verifikasi data Anda untuk langsung masuk ke Dashboard",
    dataF: "Data tidak ditemukan. Silakan mendaftar sebagai Tamu Baru.",
    handC: "Mohon isi tanda tangan terlebih dahulu!",
    errorA : "Terjadi kesalahan sistem",
    errorR: "Gagal memproses pendaftaran",
    welcome: "Selamat Menggunakan SowanQR Untuk Kunjungan Anda",
    historyDash: "Scan & Riwayat",
    yourHistory: "Riwayat Kunjungan Anda",
    yourvisits: "Belum Ada Riwayat Kunjungan",
    settingDash: "Pengaturan Akun",
    homeDash: "Beranda",
    welcomeDash: "Web Buku Tamu Buatan Murid RPL ICB Cinta Niaga ",
    morning: "Selamat Pagi",
    day: "Selamat Siang",
    afternoon: "Selamat Sore",
    night: "Selamat Malam",
    announcement: "Pengumuman Terbaru",
    createS: "Buat Kunjungan Baru",
    qr: "QR Sudah Di Scan",
    waiting: "Menunggu Di Scan",
    profile: "Pengaturan Profil",
    NIKpro: "NIK (Cannot be changed)",
    keluar: "Keluar",
    save: "Simpan",
    bahasa: "Ubah Bahasa",
    menemui: "Menemui",
    made: "Dibuat Pada",
    qrScan: "Kode QR Kamu",
    labelQr: "Tunjukkan Ke Admin Untuk di Scan",
    clear: "Selesai & Tutup",
    statusSelesai: "Selesai",
    metodeOTP: "Metode Verifikasi OTP",
    verify: "Verifikasi OTP",
    konfirmasiotp: "Konfirmasi OTP",
    digitotp: "kami telah mengirimkan 4 digit OTP ke",
    resendotp: "kirim ulang kode dalam",
    cannototp: "Belum terima kode? kirim ulang OTP",
    cancel: "Batal",
    loading: "Memuat Dashboard"

  },
  en: {
    subtitle: "Digital Visitor Book & Reservation System",
    tabNew: "Register",
    tabOld: "Login",
    labelNik: "National ID Number (NIK)",
    placeholderNik: "Enter your 16-digit NIK number",
    labelWa: "WhatsApp Number",
    placeholderWa: "example : 081222081400",
    btnCheck: "Verify Profile",
    btnChecking: "Verifying...",
    labelNama: "Full Name",
    placeholderNama: "Enter your full name",
    labelInstansi: "Institution / School",
    placeholderInstansi: "Origin institution",
    labelEmail: "Email Address",
    labelKeperluan: "Purpose of Visit",
    placeholderKeperluan: "Project Coordination / Meeting",
    labelMenemui: "Person to Meet",
    placeholderMenemui: "Teacher / Staff Name",
    labelTtd: "Digital Signature",
    btnClearTtd: "Clear Signature Canvas",
    btnSubmit: "Get QR Code",
    btnSubmitting: "Processing...",
    ticketSuccess: "Visitor Ticket Created Successfully!",
    ticketDesc: "Show this QR Code to the gate officer or receptionist.",
    btnGallery: "Save to Gallery",
    btnDashboard: "Proceed to Dashboard",
    peringatan: "Please fill in your NIK and WhatsApp number first",
    night: "Night Mode",
    noon: "Day Mode",
    registerT: "If this is your first time using SowanQR, please register first.",
    loginT: "Please verify your data to directly enter the Web",
    dataF: "Data not found. Please register as a New Guest.",
    handC: "Please fill in your signature first!",
    errorA: "A system error occurred",
    errorR: "Failed to process registration",
    welcome: "Enjoy using SowanQR for your visit",
    historyDash: "Scan & History",
    yourHistory: "Your Visit History",
    yourvisits: "There Is No History Of Your Visits Yet",
    settingDash: "Setting Account",
    homeDash: "Home",
    welcomeDash: "Guest Book Website Made by RPL ICB Cinta Niaga students",
    morning: "Good Morning",
    day: "Good Day",
    afternoon: "Good Afternoon",
    night: "Good Night",
    announcement: "latest announcement",
    createS: "Create a new visit",
    qr: "QR has been scanned",
    waiting: "Waiting For Scan",
    profile: "Profile Setting",
    NIKpro: "NIK (Cannot be changed)",
    keluar: "Exit",
    save : "Save",
    bahasa: "Change language",
    menemui: "Meet",
    made: "Made At",
    qrScan: "Your QR Code",
    labelQr: "show it to the admin to be scanned",
    clear: "Done & Close",
    statusSelesai: "Completed",
    metodeOTP: "OTP verification method",
    verify: "OTP verification",
    konfirmasiotp: "OTP confirmation",
    digitotp: "We have sent a 4 digit OTP to",
    resendotp: "resend code in",
    cannototp: "Haven't received the code yet? resend OTP",
    cancel: "Cancel",
    loading : "Load your dashboard"
  }
};
